"""add project directory fields

Revision ID: 5fe03b0855ff
Revises: 02909ea98828
Create Date: 2026-09-18 14:55:37.940292

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fe03b0855ff"
down_revision: str | Sequence[str] | None = "02909ea98828"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("directory", sa.Text(), nullable=True))
    op.add_column("projects", sa.Column("directory_status", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("agent_md", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "agent_md")
    op.drop_column("projects", "directory_status")
    op.drop_column("projects", "directory")
    # ### end Alembic commands ###
