"""add card archived_from

Revision ID: 8cf002e831a0
Revises: 5cca9eb94b5a
Create Date: 2026-09-18 20:14:33.007795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf002e831a0'
down_revision: Union[str, Sequence[str], None] = '5cca9eb94b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('archived_from', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'archived_from')
    # ### end Alembic commands ###
